import type { AuditAction } from "@/lib/api";

/** Etykiety zdarzeń dziennika działań po polsku (kontrakt §3.2). */
export const ACTION_LABELS: Record<AuditAction, string> = {
  "application.accepted": "Zgłoszenie zaakceptowane",
  "application.rejected": "Zgłoszenie odrzucone",
  "access.extended": "Przedłużono dostęp",
  "course.created": "Kurs utworzony",
  "course.updated": "Kurs zaktualizowany",
  "course.deleted": "Kurs usunięty",
  "assignment.created": "Przypisanie prowadzącego utworzone",
  "assignment.removed": "Przypisanie prowadzącego usunięte",
  "attempt.finished": "Podejście do testu zakończone",
  "attempts.reset": "Zresetowano limit podejść",
  "workshop.completed": "Warsztat zaliczony",
  "internship.accepted": "Wpis stażu zaakceptowany",
  "internship.returned": "Wpis stażu zwrócony",
  "internship.rejected": "Wpis stażu odrzucony",
  "supervisor.assigned": "Przypisano superwizora",
  "supervisor.unassigned": "Zakończono przypisanie superwizora",
  "certificate.issued": "Certyfikat wydany",
  "document.generated": "Dokument wygenerowany",
  "profile.accepted": "Profil psychologa zaakceptowany",
  "profile.returned": "Profil psychologa zwrócony",
  "profile.withdrawn": "Profil psychologa wycofany",
  "user.created": "Konto utworzone",
  "user.updated": "Konto zaktualizowane",
  "user.blocked": "Konto zablokowane",
  "user.unblocked": "Odblokowanie konta",
  "edition.updated": "Ustawienia edycji zmienione",
  "sensitive.viewed": "Wgląd w dokument wrażliwy",
  "certificate.revoked": "Certyfikat unieważniony",
  "legal_document.published": "Dokument prawny opublikowany",
  "legal_document.accepted": "Dokument prawny zaakceptowany",
  "supervision.attendance_marked": "Obecność na superwizji odnotowana",
  "supervision.slot_cancelled": "Termin superwizji odwołany",
  "user.anonymized": "Konto zanonimizowane",
  "notification_settings.updated": "Ustawienia powiadomień zmienione",
  "cooperation_request.created": "Zgłoszenie współpracy złożone",
  "cooperation_request.answered": "Odpowiedź na zgłoszenie współpracy",
  "trial_data.purged": "Dane z fazy testowej usunięte przy przejściu na produkcję",
};
