<?php

namespace Tests\Feature\Sso;

use Illuminate\Support\Str;
use Tests\Support\Sso\KeycloakTokenFactory;
use Tests\TestCase;

/**
 * `GET /api/v1/sso/whoami` accepts a Konta Niepodzielni (Keycloak) access
 * token only when it is genuinely trustworthy. Six named ways for a token
 * to fail — no token, malformed, wrong signature, expired, wrong issuer,
 * wrong audience — each its own test, each asserting 401 and, where the
 * envelope carries one, the distinguishing `error.reason.cause`.
 *
 * Hermetic on purpose: the realm is a key pair generated by this suite
 * (`KeycloakTokenFactory`), never a running identity provider — see that
 * class for how discovery/JWKS are faked instead of fetched from a server.
 */
class TokenValidatorNegativeCasesTest extends TestCase
{
    private const ROUTE = '/api/v1/sso/whoami';

    public function test_no_token_is_rejected(): void
    {
        (new KeycloakTokenFactory)->installAsRealm();

        $this->getJson(self::ROUTE)
            ->assertStatus(401)
            ->assertJsonPath('error.reason.cause', 'missing_token');
    }

    public function test_malformed_token_is_rejected(): void
    {
        (new KeycloakTokenFactory)->installAsRealm();

        $this->withHeader('Authorization', 'Bearer this-is-not-a-jwt-at-all')
            ->getJson(self::ROUTE)
            ->assertStatus(401)
            ->assertJsonPath('error.reason.cause', 'signature');
    }

    public function test_wrong_signature_is_rejected(): void
    {
        $realm = (new KeycloakTokenFactory)->installAsRealm();
        $tampered = $realm->mintWithTamperedSignature();

        $this->withHeader('Authorization', 'Bearer '.$tampered)
            ->getJson(self::ROUTE)
            ->assertStatus(401)
            ->assertJsonPath('error.reason.cause', 'signature');
    }

    /**
     * Measured, not assumed: a malformed token (wrong number of segments)
     * and a well-formed token with a tampered signature both come back as
     * `error.reason.cause = "signature"` — `TokenValidator` collapses both
     * into the same catch block and the same reason code (see its own
     * comment: "these mean 'not a token we can trust', so they collapse to
     * the same reason as a bad signature"). One shared code path, asserted
     * here rather than merged silently, per the task's instruction.
     */
    public function test_malformed_and_wrong_signature_share_the_same_reason_code(): void
    {
        $realm = (new KeycloakTokenFactory)->installAsRealm();
        $tampered = $realm->mintWithTamperedSignature();

        $malformedResponse = $this->withHeader('Authorization', 'Bearer not-a-jwt')
            ->getJson(self::ROUTE);
        $tamperedResponse = $this->withHeader('Authorization', 'Bearer '.$tampered)
            ->getJson(self::ROUTE);

        $this->assertSame(401, $malformedResponse->getStatusCode());
        $this->assertSame(401, $tamperedResponse->getStatusCode());
        $this->assertSame(
            $malformedResponse->json('error.reason.cause'),
            $tamperedResponse->json('error.reason.cause'),
            'Malformed and wrong-signature are documented as sharing one code path — a divergence here means that stopped being true.',
        );
        $this->assertSame('signature', $malformedResponse->json('error.reason.cause'));
    }

    public function test_expired_token_is_rejected(): void
    {
        $realm = (new KeycloakTokenFactory)->installAsRealm();
        $expired = $realm->mint([
            'iat' => time() - 3600,
            'exp' => time() - 1800,
        ]);

        $this->withHeader('Authorization', 'Bearer '.$expired)
            ->getJson(self::ROUTE)
            ->assertStatus(401)
            ->assertJsonPath('error.reason.cause', 'expired');
    }

    public function test_wrong_issuer_is_rejected(): void
    {
        $realm = (new KeycloakTokenFactory)->installAsRealm();
        // Signed by the same key the app's JWKS serves (so it decodes
        // cleanly) but claiming to come from a realm the app never
        // configured — the disagreement is caught after decoding, not
        // during it.
        $wrongIssuer = $realm->mint(['iss' => 'https://impostor.test/realms/other']);

        $this->withHeader('Authorization', 'Bearer '.$wrongIssuer)
            ->getJson(self::ROUTE)
            ->assertStatus(401)
            ->assertJsonPath('error.reason.cause', 'issuer');
    }

    public function test_wrong_audience_is_rejected(): void
    {
        $realm = (new KeycloakTokenFactory)->installAsRealm();
        // A token minted for some other client of the same realm — signature,
        // issuer and expiry are all fine, only the audience is wrong.
        $wrongAudience = $realm->mint(['aud' => 'account']);

        $this->withHeader('Authorization', 'Bearer '.$wrongAudience)
            ->getJson(self::ROUTE)
            ->assertStatus(401)
            ->assertJsonPath('error.reason.cause', 'audience');
    }

    public function test_empty_realm_roles_is_a_valid_state_not_an_error(): void
    {
        $realm = (new KeycloakTokenFactory)->installAsRealm();
        $token = $realm->mint(['realm_access' => ['roles' => []]]);

        $this->withHeader('Authorization', 'Bearer '.$token)
            ->getJson(self::ROUTE)
            ->assertStatus(200)
            ->assertJsonPath('roles', []);
    }

    public function test_missing_realm_access_claim_entirely_is_also_a_valid_state(): void
    {
        $realm = (new KeycloakTokenFactory)->installAsRealm();
        $payload = [
            'iss' => KeycloakTokenFactory::ISSUER,
            'aud' => ['psychon-api', 'account'],
            'azp' => 'psychon-api',
            'sub' => (string) Str::uuid(),
            'iat' => time(),
            'exp' => time() + 300,
            // deliberately no `realm_access` key at all
        ];
        $token = $realm->mint($payload);

        $this->withHeader('Authorization', 'Bearer '.$token)
            ->getJson(self::ROUTE)
            ->assertStatus(200)
            ->assertJsonPath('roles', []);
    }

    /**
     * Identity contract: binding is by `sub`, never by e-mail. Two tokens
     * that agree on every human-facing identifier (`email`) but disagree on
     * `sub` come back as two different people — the response never conflates
     * them, because the validator never reads `email` at all.
     */
    public function test_binding_is_by_sub_not_by_email(): void
    {
        $realm = (new KeycloakTokenFactory)->installAsRealm();
        $sharedEmail = 'shared@niepodzielni.test';

        $first = $realm->mint(['sub' => 'sub-person-one', 'email' => $sharedEmail]);
        $second = $realm->mint(['sub' => 'sub-person-two', 'email' => $sharedEmail]);

        $firstResponse = $this->withHeader('Authorization', 'Bearer '.$first)->getJson(self::ROUTE);
        $secondResponse = $this->withHeader('Authorization', 'Bearer '.$second)->getJson(self::ROUTE);

        $firstResponse->assertStatus(200)->assertJsonPath('sub', 'sub-person-one');
        $secondResponse->assertStatus(200)->assertJsonPath('sub', 'sub-person-two');
        $this->assertNotSame(
            $firstResponse->json('sub'),
            $secondResponse->json('sub'),
            'Same e-mail must not make two tokens resolve to the same identity.',
        );
    }
}
